### ISSUE TITLE
Installation issues 

### ISSUE THREAD

**Issue by Altai-man** [bduggan/p6-digest-sha256-native#2] opened 2020-05-11 10:49 UTC
Logs: https://gist.github.com/bazzaar/c0d1a7c6bc5e310978e265bc2727e27b

Maybe escaping is missing somewhere?

**Comment by melezhik** [comment] 2020-05-11 13:17
Works on RakuDist/debian. On the same version of Rakudo

http://repo.westus.cloudapp.azure.com/sparky/report/debian/737

**Comment by Altai-man** [comment] 2020-05-11 13:29
Yes, that's what I saw as well. But the log is what a real user has reported.
I wonder if there is some subtle bug on some environments.

>[Digest::SHA256::Native] Command: /opt/rakudo-pkg/bin/rakudo -e require '/home/bazzaar/.zef/store/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/Build.pm'; ::('Build').new.build('/home/bazzaar/.zef/store/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03') ?? exit(0) !! exit(1);

Does not really look to me like a correct invocation.

**Comment by melezhik** [comment] 2020-05-11 13:46
maybe zef version specific bug?

**Comment by Altai-man** [comment] 2020-05-11 13:50
https://github.com/ugexe/zef/blob/d39ca4d278b57046618b579e9287b299079e90bc/lib/Zef/Service/Shell/DistributionBuilder.pm6#L16-L21
feels like something. I wonder if it doesn't escape code properly somehow.

**Comment by melezhik** [comment] 2020-05-11 13:54
RakuDist's zef version: 

```
13:13:37 05/11/2020 [bash: zef version] v0.8.4
```

Let's compare with the VM's zef version

**Comment by bduggan** [comment] 2020-05-12 12:59
I tried the latest version of zef on OS/X (v0.8.4, 0414984b7), as well as an older version (v0.8.2) but couldn't reproduce this.

**Comment by melezhik** [comment] 2020-05-12 15:50
so we need to know the version of zef used when the error happened.

**Comment by bazzaar** [comment] 2020-05-12 20:47
bazzaar@linux:~> zef --version
v0.8.4

(this just reproduced again now)
bazzaar@linux:~> zef install Digest::SHA256::Native
===> Searching for: Digest::SHA256::Native
===> Building: Digest::SHA256::Native:ver<0.03>
[Digest::SHA256::Native] ===SORRY!===
[Digest::SHA256::Native] No such method 'CALL-ME' for invocant of type 'Str'
===> Building [FAIL]: Digest::SHA256::Native:ver<0.03>
Aborting due to build failure: Digest::SHA256::Native:ver<0.03> (use --force-build to override)

Background : 
OK, so the initial fail, happened after upgrading to the 2020.05.1 point release (using the Opensuse Leap 15.2 system package manager). The new release (rakudo and zef) found and listed all the additional modules I'd just installed only hours before on top of the 2020-05 release.  Digest::SHA256::Native was the first module I tried to install after the upgrade. I don't remember if I'd logged out / shut down the machine in between times. However, I've successfully installed two other modules since : 
bazzaar@linux:~> zef install Log::Async
===> Searching for: Log::Async
===> Testing: Log::Async:ver<0.0.6>
===> Testing [OK] for Log::Async:ver<0.0.6>
===> Installing: Log::Async:ver<0.0.6>
bazzaar@linux:~> zef install Net::ZMQ
===> Searching for: Net::ZMQ
===> Testing: Net::ZMQ:ver<0.8>
===> Testing [OK] for Net::ZMQ:ver<0.8>
===> Installing: Net::ZMQ:ver<0.8>

Anyone have any suggestion for what I could try next?

**Comment by Altai-man** [comment] 2020-05-13 09:10
Not all modules have build step. I think you want to look up modules with `Build.pm` in the repo or something, but I really don't remember such a module quickly...

**Comment by bazzaar** [comment] 2020-05-13 10:25
Thanks (Altai-man, melezhic, bduggan) for investigating, it seems that this probably isn't a digest-sha256-native specific issue, as I'm now finding other errors cropping up. To be clear, I saw no such errors loading a whole raft of modules onto 2020.05, this seems to have only surfaced since upgrading to the point release.

bazzaar@linux:~> zef install AccessorFacade
===> Searching for: AccessorFacade
===> Testing: AccessorFacade:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
[AccessorFacade] ===SORRY!=== Error while compiling /home/bazzaar/.zef/store/AccessorFacade-0.0.9.tar.gz/AccessorFacade-0.0.9/t/001-meta.t
[AccessorFacade] An exception occurred while evaluating a BEGIN
[AccessorFacade] at /home/bazzaar/.zef/store/AccessorFacade-0.0.9.tar.gz/AccessorFacade-0.0.9/t/001-meta.t:11
[AccessorFacade] Exception details:
[AccessorFacade]   ===SORRY!=== Error while compiling /home/bazzaar/.zef/store/AccessorFacade-0.0.9.tar.gz/AccessorFacade-0.0.9/home#sources/E6B391CCF8844EE61A10DCED6E801E9A713D13F6 (Test::META)
[AccessorFacade]   No such method 'update' for invocant of type 'Block'
[AccessorFacade]   at /home/bazzaar/.zef/store/AccessorFacade-0.0.9.tar.gz/AccessorFacade-0.0.9/home#sources/E6B391CCF8844EE61A10DCED6E801E9A713D13F6 (Test::META):70
[AccessorFacade]     in block  at t/001-meta.t line 12
===> Testing [FAIL]: AccessorFacade:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0>
Aborting due to test failure: AccessorFacade:ver<0.0.9>:auth<github:jonathanstowe>:api<1.0> (use --force-test to override)

**Comment by bazzaar** [comment] 2020-05-16 13:54
I just found that I had no repl (even though zef lists Readline as being installed)

to enter the repl, I type raku, press enter, when I do, nothing happens, it just hangs without a prompt.

Maybe this ties in with the issues I've been seeing with zef (https://github.com/bduggan/p6-digest-sha256-native/issues/2)    

It seems like although zef lists Readline as being locally installed, rakudo is not really able to use it?
                            
Ever since I upgraded to the new rakudo/zef package (2020.05.1).

So I just did a 'zef install --force-install Readline' even though zef said 'All candidates are currently installed, No reason to proceed.'

.... and now the repl works, when i type raku and enter.

So it appears that modules installed on top of 2020.05, are not being properly accessed once rakudo/zef 2020.05.1 package is installed.

**Comment by Altai-man** [comment] 2020-05-17 22:04
I am sure this repo is not the right place, but not sure where this should be.
First of all, the original issue is still reproducible?

**Comment by bazzaar** [comment] 2020-05-17 22:22
As of 5mins ago, yes (see below). However I am resigned to to just --force-install'ing all the modules I'd installed previously on 2020.05. I'm not sure, if folks would be impacted if there were to be a 2nd point release, or even a point release for 2020.06.

I agree, this isn't the repo to document this issue (instead zef/rakudo probably?)

bazzaar@localhost:~> zef install --debug Digest::SHA256::Native
===> Searching for: Digest::SHA256::Native
===> Found: Digest::SHA256::Native:ver<0.03> [via Zef::Repository::LocalCache]
===> Dependencies: LibraryMake
===> Filtering: Digest::SHA256::Native:ver<0.03>
===> Filtering [OK] for Digest::SHA256::Native:ver<0.03>
===> Building: Digest::SHA256::Native:ver<0.03>
[Digest::SHA256::Native] Building with plugin: Zef::Service::Shell::LegacyBuild+{<anon|1>}
[Digest::SHA256::Native] Command: /opt/rakudo-pkg/bin/rakudo -e require '/home/bazzaar/.zef/store/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03/Build.pm'; ::('Build').new.build('/home/bazzaar/.zef/store/Digest-SHA256-Native-0.03.tar.gz/Digest-SHA256-Native-0.03') ?? exit(0) !! exit(1);
[Digest::SHA256::Native] ===SORRY!===
[Digest::SHA256::Native] No such method 'CALL-ME' for invocant of type 'Str'
===> Building [FAIL]: Digest::SHA256::Native:ver<0.03>
Aborting due to build failure: Digest::SHA256::Native:ver<0.03> (use --force-build to override)

**Comment by bduggan** [comment] 2020-05-29 16:11
Things are working fine as far as I can tell, so I'm going to close this; I can't reproduce it
```
~ $ raku -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.
~ $ zef install Digest::SHA256::Native
===> Searching for: Digest::SHA256::Native
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Building: Digest::SHA256::Native:ver<0.03>
===> Building [OK] for Digest::SHA256::Native:ver<0.03>
===> Testing: Digest::SHA256::Native:ver<0.03>
===> Testing [OK] for Digest::SHA256::Native:ver<0.03>
===> Installing: Digest::SHA256::Native:ver<0.03>
~ $ zef --version
v0.8.4
```

**Closed by bduggan** 2020-05-29 16:11 UTC
